### ISSUE TITLE
Using your work and audio interaction to blow dust

### ISSUE THREAD

**Issue by Wewill** [data-sapiens/SparkAR-BlowBubbles#1]
Hey, That's not an issue, but I'm new to Spark and I'm wondering if you could guide to use your work to blow dust instead of bubbles ? I tried to change the texture without success. 
Best regards !

**Comment by lassemt** [comment]
Hi @Wewill,

All you should need to do is to comment out the `this.setupMatBubble();´ on line 42, then you should be free to style the particles as you feel using the patch editor or whatever.

https://github.com/data-sapiens/SparkAR-BlowBubbles/blob/2c7327ed0f38a277448bbc00e9307b7de6cb5bf1/scripts/script.js#L42
